steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - --target
      - deploy
      - --tag=gcr.io/$PROJECT_ID/gke-grpc-sample-server:$BUILD_ID
      - .
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - gcr.io/$PROJECT_ID/gke-grpc-sample-server:$BUILD_ID
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - beta
      - container
      - clusters
      - get-credentials
      - gke-grpc-sample
      - --zone=asia-northeast1-a
      - --project=$PROJECT_ID
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - set
      - image
      - deployment/api-deployment
      - api-container=gcr.io/$PROJECT_ID/gke-grpc-sample-server:$BUILD_ID
    env:
      - "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=gke-grpc-sample"
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - set
      - image
      - cronjob/hello
      - batch-container=gcr.io/$PROJECT_ID/gke-grpc-sample-server:$BUILD_ID
    env:
      - "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=gke-grpc-sample"
