version: "3.7"
services:
  app:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
      target: local-dev
    image: gke-grpc-sample-local:latest
    volumes:
      - .:/app
      - .mod:/go/pkg/mod
    working_dir: /app
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    command:
      - "sh"
      - "-c"
      - "go run /app/main.go api"
    ports:
      - "3000:80"
      - "4000:4000"
    environment:
      - WEB_PORT=80
      - GRPC_PORT=4000
      - TZ=Asia/Tokyo
      - GO_ENV=/app/env

  batch:
    build:
      context: .
      dockerfile: Dockerfile
      target: local-dev
    image: gke-grpc-sample-batch-local:latest
    volumes:
      - .:/app
      - .mod:/go/pkg/mod
    working_dir: /app
    environment:
      - TZ=Asia/Tokyo
      - GO_ENV=/app/env

  grpcui:
    build:
      context: grpcui/.
      dockerfile: Dockerfile
      target: local-dev
    image: gke-grpc-sample-grpcui-local:latest
    volumes:
      - ./grpcui/script/.:/app
      - .mod:/go/pkg/mod
    working_dir: /app
    tty: true
    command:
      - "sh"
      - "-c"
      - "./start.sh"
    ports:
      - "8080:8080"
    environment:
      - GRPC_WEB_SERVER=app:80
      - GRPC_SERVER=app:4000

  web:
    init: true
    build:
      context: web/.
      dockerfile: Dockerfile
      target: local-dev
    image: gke-grpc-sample-web-local:latest
    volumes:
      - ./web/.:/app
    working_dir: /app
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    command:
      - "sh"
      - "-c"
      - "npm start"
    tty: true
    ports:
      - "3030:3000"
