version: "3.7"
services:
  app:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
      target: local-dev
    image: grpc-k8s-sample-local:latest
    volumes:
      - .:/app
      - .mod:/go/pkg/mod
    working_dir: /app
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    command:
      - "sh"
      - "-c"
      - "GO_ENV=/app/env go run /app/main.go"
    ports:
      - "3000:80"
      - "4000:4000"
    environment:
      - WEB_PORT=80
      - GRPC_PORT=4000
      - TZ=Asia/Tokyo

  grpcui:
    build:
      context: grpcui/.
      dockerfile: Dockerfile
      target: local-dev
    image: grpcui-local:latest
    volumes:
      - ./grpcui/script/.:/app
      - .mod:/go/pkg/mod
    working_dir: /app
    tty: true
    command:
      - "sh"
      - "-c"
      - "./start.sh"
    ports:
      - "8080:8080"
    environment:
      - GRPC_WEB_SERVER=app:80
      - GRPC_SERVER=app:4000
