---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: gcr.io/akiho-playground/api:${VER}
          command: ["./main"]
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/gcp/credentials.json
            - name: WEB_PORT
              value: 80
            - name: GRPC_PORT
              value: 4000
            - name: TZ
              value: Asia/Tokyo
          volumeMounts:
            - name: gcp-credentials
              mountPath: /var/secrets/gcp
              readOnly: true
          ports:
            - containerPort: 80
            - containerPort: 4000
          readinessProbe:
            httpGet:
              path: /health_check
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: api-node-port
spec:
  type: NodePort
  ports:
    - name: "grpc-web-port"
      protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: api

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: api-ip
spec:
  backend:
    serviceName: api-node-port
    servicePort: 80
